kind: ConfigMap
apiVersion: v1
metadata:
  name: merchant-payment-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: payment
    service: merchant-payment
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: merchant-payment
  namespace: {{ .Values.namespace }}
  labels:
    app: payment
    service: merchant-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: merchant-payment
  template:
    metadata:
      labels:
        app: payment
        service: merchant-payment
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "merchant-payment-api"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: merchant-payment-api
          image: kapitan123/merchant-payment.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 81
              protocol: TCP
          envFrom:
            - configMapRef:
                name: merchant-payment-cm
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---

kind: Service
apiVersion: v1
metadata:
  name: merchant-payment-api
  namespace: {{ .Values.namespace }}
  labels:
    app: payment
    service: merchant-payment
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
      protocol: TCP
      name: http
    - port: 3500
      targetPort: 3500
      nodePort: 30040
      protocol: TCP
      name: dapr-http
    - port: 50001
      targetPort: 50001
      nodePort: 30041
      protocol: TCP
      name: dapr-grpc
  selector:
    service: merchant-payment
