apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # Secrets are BASE64 encoded
  # Connection strings are temporarily injected using environment variables
  # while waiting for https://github.com/dapr/dotnet-sdk/issues/779 to get fixed.
  RedisPassword: ZSRoMHAwbkRAcHI=
