apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: payment-secretstore
  namespace: payment
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: payment-secrets.json
  - name: nestedSeparator
    value: "."
